<?php
$creditbalance = $this->getData('creditbalance');
$orders = $this->getData('orders');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) {
?>
  <span class="info">Available Credit: <br> <b><?php echo $creditbalance ?></span>
  <span class="info">Order History</span> <br> <b><?php echo $orders ?></span>
  <span class="action more icon">My Account</span> </span> </a>
<?php
} else {
?>
  <span class="info">Please login or register now.</span>
  <span class="action more icon">My Account</span> </span> </a>
<?php
}
?>
